### ISSUE TITLE
Add tests in edx-sysadmin plugin

### ISSUE THREAD

**Issue by HamzaIbnFarooq** [mitodl/edx-sysadmin#11]
### Acceptance criteria
- [ ] Move tests from edx-platform to edx-sysadmin
- [ ] Configure tests to be run on CI, we have done some similar work in rapid-response (https://github.com/mitodl/rapid-response-xblock/blob/master/.github/workflows/ci.yml#L15-L27) that might help.

**Comment by arslanashraf7** [comment]
@pdpinch, @HamzaIbnFarooq , I've created a new issue for fixing one TestSuit that we pulled from edX and it might require some amount of refactoring, which could basically be the extension to this issue.

FYI, Other tests are fixed in associated PR(https://github.com/mitodl/edx-sysadmin/pull/19) which required less refactoring.

Please let me know if this is OK with you both.

**Comment by arslanashraf7** [comment]
Closing, The associated PR is merged and for one test suit that needed refactoring, we'll be working on it as a separate ticket https://github.com/mitodl/edx-sysadmin/issues/20.
