### ISSUE TITLE
Refactor and pass test_sysadmin tests

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/edx-sysadmin#20]
This ticket is an extension to https://github.com/mitodl/edx-sysadmin/issues/11 where we pulled reminding sysadmin tests from edX and also integrated CI and devstack to run the tests properly.

The PR (https://github.com/mitodl/edx-sysadmin/pull/19) adds most of the integration-related work and gets to pass course-related tests except for https://github.com/mitodl/edx-sysadmin/blob/00fa13f30d7e8b89fc759f5867dfc00f24dff892/tests/test_sysadmin.py TestSuit because this one would require a major refactoring.

As per the context and amount of refactoring, I'm are creating this as a separate ticket to refactoring of  https://github.com/mitodl/edx-sysadmin/blob/00fa13f30d7e8b89fc759f5867dfc00f24dff892/tests/test_sysadmin.py.

**Acceptance Criteria:**
- [ ] Tests in https://github.com/mitodl/edx-sysadmin/blob/00fa13f30d7e8b89fc759f5867dfc00f24dff892/tests/test_sysadmin.py should pass

**Comment by umarmughal824** [comment]
I'm blocked here because while running test cases it gives me webpack errors that requires to compile assest for openedx. But while compiling assets, I could see the `edx-platfrom` requirments files is broken due to some broken packages like

```
git+https://github.com/edx/MongoDBProxy.git@d92bafe9888d2940f647a7b2b2383b29c752f35a#egg=MongoDBProxy==0.1.0+edx.2  # via -r requirements/edx/testing.txt

ERROR: Could not find a version that satisfies the requirement mongodbproxy (unavailable)
ERROR: No matching distribution found for mongodbproxy (unavailable)
```

Here is the reference for it.
https://github.com/mitodl/edx-sysadmin/pull/26/checks?check_run_id=2399615909#step:6:497
