### ISSUE TITLE
Timeouts loading /courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sysadmin#50]
It can take a long time for /syadmin/courses to load when there are a lot of courses (1000+ on staging, for example). Sometimes the page can timeout.

**Comment by arslanashraf7** [comment]
@pdpinch, What would your thoughts be on the possible solutions for this problem:

1. We increase the timeout for the request.
2. We add pagination for the courses in this tab, But we'll have to decide upon some factors e.g.

    1. Number of items/courses per page/load
    2. What should be shown as part of UX, A `Load More` button or `page number slider`.

**Comment by pdpinch** [comment]
I think option 2 is more sustainable. I think 20 courses per page is reasonable. 

I don't think a page number slider is going to be a useful UX, because users can't guess which page the course they are interested in will be on. I would prefer a "Load More" that loads the next page and appends it. So, with patience, I could load the entire list. 

What do you think?

**Comment by HamzaIbnFarooq** [comment]
While working on this issue I have encountered some issues which I think are worth sharing so below are my findings till now:

**Why load timeout occurs?**

In current implementation whenever a sysadmin opens courses tab the backend `fetches all courses from edX's modulestore` and runs `git log -1 --format=format:{ "commit": "%H", "author": "%an %ae", "date": "%ad"}` on all the courses one by one. So both **1)** fetching of all courses and **2)** getting git log of each course collectively causes load timeout.

**Can we add pagination for modulestore?**

Unfortunately, `edX's modulestore doesn't seem to have any method to fetch limited amount of courses from mongo` to do pagination rather it always fetches all the courses. 

edX modulestore has two methods to fetch courses
**1)** [get_courses](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/modulestore/mixed.py#L305) (`we are currently using this method`)
**2)** [get_course_summaries](https://github.com/edx/edx-platform/blob/master/common/lib/xmodule/xmodule/modulestore/mixed.py#L285) (`It seems like a bit lighter than get_courses as it fetches relatively smaller data from mongo`)

both the methods do not support any kind of sorting and filtering (other than filtering on course organization and course-id which is of no use in our scenario).

**Can we use any alternative of `modulestore` like [CourseOverview](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/content/course_overviews/models.py#L48)?**

Seems like `NO`, because CourseOverview only contains information of live courses. Let's say if you have just imported a course from git or created a course on studio, until you explicitly mark its content live it will not be available in CourseOverview.

We can push all modulestore courses to CourseOverview by using a management command named [generate_course_overview](https://github.com/edx/edx-platform/blob/master/openedx/core/djangoapps/content/course_overviews/management/commands/generate_course_overview.py#L24) but using this command will make all the courses publically available on dashboard so it's not a good solution either.

### Solution:

**Approach 1:**
We can't ignore modulestore, we have to fetch all courses from modulestore and send them to the client-side. Then on each `load more button` press we have to send specific number of course Id's (let's say 20) to backend via an API to run `git log -1 --format=format:{ "commit": "%H", "author": "%an %ae", "date": "%ad"}` command on them and return the details to be appended in the table.

**OR**

**Approach 2:**
We have to fetch all courses from modulestore and send them to the client-side. The client-side will have a table populating all the courses but the git commit information will not be present in table. Each table row will have a load button to load information regarding just that specific course.

FYI: @pdpinch

**Comment by pdpinch** [comment]
Thanks for the research Hamza. 

From the user perspective, I like approach 2 because we don’t spend the time getting the commit info unless the user requests it. 
> Approach 2:
> We have to fetch all courses from modulestore and send them to the client-side. The client-side will have a table populating all the courses but the git commit information will not be present in table. Each table row will have a load button to load information regarding just that specific course.
>

**Comment by pdpinch** [comment]
I think this can be closed? @arslanashraf7 @HamzaIbnFarooq
