### ISSUE TITLE
Nutmeg: git import does not update course outline

### ISSUE THREAD

**Issue by pdpinch** [mitodl/edx-sysadmin#71]
In the nutmeg release of open edX, there was a persistence layer added to course outlines, to load them from mysql (relatively fast) instead of mongo (slow). The course outline should be created or updated whenever a course imports. 

In our testing, the course outline _does_ get created or updated when a course is imported into studio, but it doesn't get updated when a course is imported via git import. 

You can test this by adding a new chapter to a course in git and importing it. The new chapter won't appear on the course home page, where the outline is displayed. Publishing the course manually through studio should update the course outline.

**Comment by asadali145** [comment]
Update:
 Had a few discussions with Arslan on this issue. Here are the findings after debugging/R&D:

CASE 1:
- If a course is being imported for the `first time` (Like the course does not exist in the system before), then CourseOutline is missing and the course home fails to load. In this case, It requires us to create CourseOutline in MySQL. We can do so by using `update_course_outline ` as mentioned in this [readme](https://github.com/openedx/edx-platform/blob/db32ff2cdf678fa8edd12c9da76a76eef0478614/openedx/core/djangoapps/content/learning_sequences/README.rst).
- After CourseOutline creation, course home loads but we cannot see CourseOutline due to Course blocks cache.
- We can update the cache by sending a `course_published` signal that updates the cache and the course outline works fine.

CASE 2:

- Course exists and we update it using the git. In this case, CourseOutline is already created but we will have to update it using the `update_course_outline ` command.
- We also need to send a `course_published` to update the cache as well.

Another issue is that a `course_published` signal is raised while importing a course but it is not updating the cache properly. We need to figure out this issue.
